SENDGRID_PASSWORD: oxyctyj3
SENDGRID_USERNAME: app35850229@heroku.com
DEVISE_SECRET_KEY: 
AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY: 
development:
  AWS_BUCKET: wpb-pgh-bloccit-development
production:
  AWS_BUCKET: wpb-pgh-bloccit-production
